spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/distributedb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  config:
     import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


